### ISSUE TITLE
Build Python wheels for Apple Silicon M1

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#165]
Links:
- How it is done in Rust-analyzer - https://github.com/rust-analyzer/rust-analyzer/pull/6989/files
- more notes - https://github.com/shepmaster/rust/blob/silicon/silicon/README.md

```
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
        profile: minimal
        override: true
```

Related to #159
